-- MySQL Script generated by MySQL Workbench
-- Thu Sep 15 22:23:12 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `e_mail` VARCHAR(40) NOT NULL,
  `login` VARCHAR(45) NULL,
  `sobrenome` VARCHAR(45) NULL,
  `endereço` VARCHAR(45) NULL,
  `telefone` INT NULL,
  `login` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`e_mail`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ONG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ONG` (
  `cnpj` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `site` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`cnpj`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`animal` (
  `id_Animal` INT NOT NULL,
  `dono` VARCHAR(45) NULL,
  `especie` VARCHAR(45) NULL,
  `porte` VARCHAR(45) NULL,
  `idade` INT NULL,
  `nome` VARCHAR(45) NULL,
  `caracteristicas` VARCHAR(45) NULL,
  `raca` VARCHAR(45) NULL,
  `usuario_e_mail` VARCHAR(40) NOT NULL,
  `ONG_cnpj` INT NOT NULL,
  PRIMARY KEY (`id_Animal`, `usuario_e_mail`, `ONG_cnpj`),
  INDEX `fk_animal_usuario_idx` (`usuario_e_mail` ASC) VISIBLE,
  INDEX `fk_animal_ONG1_idx` (`ONG_cnpj` ASC) VISIBLE,
  CONSTRAINT `fk_animal_usuario`
    FOREIGN KEY (`usuario_e_mail`)
    REFERENCES `mydb`.`usuario` (`e_mail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animal_ONG1`
    FOREIGN KEY (`ONG_cnpj`)
    REFERENCES `mydb`.`ONG` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
